ci:
    autofix_commit_msg: 'refactor(lint): apply automatic lint fixes'
    autoupdate_commit_msg: 'chore(deps): bump pre-commit linter versions'

default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace

# python
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.0.3
    hooks:
    -   id: pylint
        args:
        - --load-plugins=pylint.extensions.mccabe
        - --max-complexity=10
        - --max-line-length=109
        - --max-args=10
        - --score=n
        - -d broad-except
        - -d duplicate-code
        - -d fixme
        - -d import-error
        - -d import-only-modules
        - -d inconsistent-return-statements
        - -d invalid-name
        - -d locally-disabled
        - -d missing-docstring
        - -d redefined-outer-name
        - -d too-few-public-methods
        - -d try-except-raise
        - -d ungrouped-imports  # conflicts with reorder-python-imports
        - -d wrong-import-order  # conflicts with reorder-python-imports
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: [--py311-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
-   repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
    -   id: yesqa
        # N.B. keep these in sync with flake8, otherwise yesqa will remove
        # required noqa's related to these plugins
        additional_dependencies: &flake8deps
        - flake8-2020==1.8.1
        - flake8-broken-line==1.0.0
        - flake8-builtins==2.1.0
        - flake8-commas==2.1.0
        - flake8-comprehensions==3.13.0
-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args: [-a, -i, -p2]
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args:
        - --ignore=D1,D203,D205,D212,D400,D401,D404,D407,D412,D413
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: *flake8deps
        args:
        # https://www.flake8rules.com/
        # E501: Line too long. Covered by autopep8.
        # E741: Do not use variables named 'I', 'O', or 'l'.
        - --ignore=E501,E741
-   repo: local
    hooks:
    -   id: poetry-check
        name: check pyproject.toml validity
        description: 'Validate the structure of the pyproject.toml file'
        entry: bash -c 'set -e; for toml in "$@"; do pushd ./${toml%pyproject.toml}; poetry check; popd; done' --
        language: python
        additional_dependencies:
        - poetry>=1.2.0
        pass_filenames: true
        files: 'pyproject\.toml$'
    -   id: poetry-use-version-ranges
        name: avoid using carets for version ranges
        description: 'Avoid using carets for version ranges'
        entry: '\^'
        language: pygrep
        types: [toml]
        files: 'pyproject.toml$'
    -   id: pytest-fixtures-require-scope
        name: ensure pytest fixture scopes are explicitly set
        description: 'Ensure we explicitly set pytest fixture scopes'
        entry: '@pytest\.fixture( |\n|(\(\)))'
        language: pygrep
        types: [python]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations

# rst
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal

# json
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.3
  hooks:
    - id: check-github-workflows
    - id: check-renovate
      additional_dependencies:
      - pyjson5
