version: 2

jobs:
  lint:
    docker:
      - image: python:3.7.1-alpine3.8
    steps:
      - run: apk add -U git
      - checkout
      - run: pip install pre-commit
      - run: pre-commit run --all-files

workflows:
  version: 2
  run-jobs:
    jobs:
      - lint
